name: 'Test Selenium IDE'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - trunk
jobs:
  test:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    if: github.repository == 'seleniumhq/selenium-ide'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -r i
      - name: Build side-runner and selenium-ide
        run: npm run build
      - name: Install xvfb
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Run all tests
        if: matrix.os != 'windows-latest'
        run: |
          npm run test:ci
      - name: Run all tests on Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm run test:ci:windows

